# Generated by Django 5.0.2 on 2024-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='adults',
            new_name='adult_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='child_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(default='Room 1', max_length=50),
        ),
    ]
