# Generated by Django 5.0.2 on 2024-12-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelapp', '0002_rename_adults_booking_adult_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='checkin',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='checkout',
        ),
    ]
