# Generated by Django 5.0.2 on 2024-12-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelapp', '0003_rename_check_in_booking_checkin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
